// Code generated by MockGen. DO NOT EDIT.
// Source: user_service_interface.go
//
// Generated by this command:
//
//	mockgen -source=user_service_interface.go -destination=../../mocks/user_service_mock.go -package=mocks
//
// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "example.com/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockUserServiceInterface is a mock of UserServiceInterface interface.
type MockUserServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUserServiceInterfaceMockRecorder
}

// MockUserServiceInterfaceMockRecorder is the mock recorder for MockUserServiceInterface.
type MockUserServiceInterfaceMockRecorder struct {
	mock *MockUserServiceInterface
}

// NewMockUserServiceInterface creates a new mock instance.
func NewMockUserServiceInterface(ctrl *gomock.Controller) *MockUserServiceInterface {
	mock := &MockUserServiceInterface{ctrl: ctrl}
	mock.recorder = &MockUserServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserServiceInterface) EXPECT() *MockUserServiceInterfaceMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockUserServiceInterface) Add(ctx context.Context, name string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, name)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Add indicates an expected call of Add.
func (mr *MockUserServiceInterfaceMockRecorder) Add(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockUserServiceInterface)(nil).Add), ctx, name)
}

// Delete mocks base method.
func (m *MockUserServiceInterface) Delete(ctx context.Context, id string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockUserServiceInterfaceMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUserServiceInterface)(nil).Delete), ctx, id)
}

// GetUserByAuthToken mocks base method.
func (m *MockUserServiceInterface) GetUserByAuthToken(ctx context.Context, authToken string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByAuthToken", ctx, authToken)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByAuthToken indicates an expected call of GetUserByAuthToken.
func (mr *MockUserServiceInterfaceMockRecorder) GetUserByAuthToken(ctx, authToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByAuthToken", reflect.TypeOf((*MockUserServiceInterface)(nil).GetUserByAuthToken), ctx, authToken)
}

// GetUserByUserId mocks base method.
func (m *MockUserServiceInterface) GetUserByUserId(ctx context.Context, id string) (domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByUserId", ctx, id)
	ret0, _ := ret[0].(domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByUserId indicates an expected call of GetUserByUserId.
func (mr *MockUserServiceInterfaceMockRecorder) GetUserByUserId(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByUserId", reflect.TypeOf((*MockUserServiceInterface)(nil).GetUserByUserId), ctx, id)
}

// GetUserRanking mocks base method.
func (m *MockUserServiceInterface) GetUserRanking(ctx context.Context) ([]*domain.UserRanking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserRanking", ctx)
	ret0, _ := ret[0].([]*domain.UserRanking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserRanking indicates an expected call of GetUserRanking.
func (mr *MockUserServiceInterfaceMockRecorder) GetUserRanking(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserRanking", reflect.TypeOf((*MockUserServiceInterface)(nil).GetUserRanking), ctx)
}

// UpdateUser mocks base method.
func (m *MockUserServiceInterface) UpdateUser(ctx context.Context, user domain.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockUserServiceInterfaceMockRecorder) UpdateUser(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockUserServiceInterface)(nil).UpdateUser), ctx, user)
}
