name: Generate mocks
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
               go install go.uber.org/mock/mockgen@latest
      - name: Generate mocks
        run: |
          
          for dir in "/app/application/middlewares" "/app/application/services" "/app/interface/handlers"; do
          
            for file in $(find $dir -name '*.go' ! -name '*_interface.go'); do
              mockgen -source=$file -destination=mocks/
            done
          
          done