name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.1

      - name: Install dependencies
        run: |
          go install github.com/golang/mock/mockgen@latest

      - name: Generate mocks
        run: |
          cd app
          go generate ./...