name: Generate Mocks

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:

  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.1

      - name: Install mockgen
        run: go install go.uber.org/mock/mockgen@latest

      - name: Generate mocks
        run: |
          cd app
          go generate ./...