name: Generate Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Generate test files
        run: |
          go get -u github.com/cweill/gotests/...
          find . -name "*.go" ! -path "./vendor/*" -exec gotests -all -w {} +
